const routes = [
  {
    to: "Pithoragarh",
    from: "Delhi",
    time: 10,
    distance: 450,
    extraPrice: 15,
    price: 2000,
  },
  {
    to: "Delhi",
    from: "Pithoragarh",
    time: 10,
    distance: 450,
    extraPrice: 15,
    price: 2000,
  },
  {
    to: "Pithoragarh",
    from: "Haldwani",
    time: 6,
    distance: 170,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "Haldwani",
    from: "Pithoragarh",
    time: 6,
    distance: 170,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
  {
    to: "",
    from: "",
    time: 6,
    distance: 100,
    extraPrice: 12,
    price: 1500,
  },
];

export const routesByCity = [
  {
    cityName: "Haldwani/Rudrapur",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Roorkee",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Pithoragarh",
        time: 10,
        distance: 450,
        extraPrice: 15,
        price: 2000,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
    ],
  },
  {
    cityName: "Pithoragarh",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haldwani/Rudrapur",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Roorkee",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
    ],
  },
  {
    cityName: "Delhi",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haldwani",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Pithoragarh",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Almora",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
    ],
  },
  {
    cityName: "Almora",
    routes: [
      {
        to: "Dehradun",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haldwani",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Pithoragarh",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Delhi",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Haridwaar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
      {
        to: "Bageshwar",
        time: 6,
        distance: 170,
        extraPrice: 12,
        price: 1500,
      },
    ],
  },
];
